# Generated by Django 4.2.7 on 2023-12-18 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dijeta',
            fields=[
                ('imedijeta', models.CharField(db_column='ImeDijeta', max_length=200, primary_key=True, serialize=False)),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=2048, null=True)),
                ('minenergija', models.DecimalField(blank=True, db_column='MinEnergija', decimal_places=5, max_digits=10, null=True)),
                ('maxenergija', models.DecimalField(blank=True, db_column='MaxEnergija', decimal_places=5, max_digits=10, null=True)),
                ('minmasnoce', models.DecimalField(blank=True, db_column='MinMasnoce', decimal_places=5, max_digits=10, null=True)),
                ('maxmasnoce', models.DecimalField(blank=True, db_column='MaxMasnoce', decimal_places=5, max_digits=10, null=True)),
                ('minzmkiseline', models.DecimalField(blank=True, db_column='MinZMKiseline', decimal_places=5, max_digits=10, null=True)),
                ('maxzmkiseline', models.DecimalField(blank=True, db_column='MaxZMKiseline', decimal_places=5, max_digits=10, null=True)),
                ('minugljikohidrati', models.DecimalField(blank=True, db_column='MinUgljikohidrati', decimal_places=5, max_digits=10, null=True)),
                ('maxugljikohidrati', models.DecimalField(blank=True, db_column='MaxUgljikohidrati', decimal_places=5, max_digits=10, null=True)),
                ('minseceri', models.DecimalField(blank=True, db_column='MinSeceri', decimal_places=5, max_digits=10, null=True)),
                ('maxseceri', models.DecimalField(blank=True, db_column='MaxSeceri', decimal_places=5, max_digits=10, null=True)),
                ('minbjelancevine', models.DecimalField(blank=True, db_column='MinBjelancevine', decimal_places=5, max_digits=10, null=True)),
                ('maxbjelancevine', models.DecimalField(blank=True, db_column='MaxBjelancevine', decimal_places=5, max_digits=10, null=True)),
                ('minsol', models.DecimalField(blank=True, db_column='MinSol', decimal_places=5, max_digits=10, null=True)),
                ('maxsol', models.DecimalField(blank=True, db_column='MaxSol', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxenergija', models.DecimalField(blank=True, db_column='DnevniMaxEnergija', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxmasnoce', models.DecimalField(blank=True, db_column='DnevniMaxMasnoce', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxzmkiseline', models.DecimalField(blank=True, db_column='DnevniMaxZMKiseline', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxugljikohidrati', models.DecimalField(blank=True, db_column='DnevniMaxUgljikohidrati', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxseceri', models.DecimalField(blank=True, db_column='DnevniMaxSeceri', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxbjelancevine', models.DecimalField(blank=True, db_column='DnevniMaxBjelancevine', decimal_places=5, max_digits=10, null=True)),
                ('dnevnimaxsol', models.DecimalField(blank=True, db_column='DnevniMaxSol', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Dijeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dodatneoznake',
            fields=[
                ('idozn', models.IntegerField(db_column='IDOzn', primary_key=True, serialize=False)),
                ('opisozn', models.CharField(blank=True, db_column='OpisOzn', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'DodatneOznake',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('korisnickoime', models.CharField(db_column='KorisnickoIme', max_length=50, primary_key=True, serialize=False)),
                ('lozinka', models.CharField(blank=True, db_column='Lozinka', max_length=200, null=True)),
                ('ime', models.CharField(blank=True, db_column='Ime', max_length=50, null=True)),
                ('prezime', models.CharField(blank=True, db_column='Prezime', max_length=50, null=True)),
                ('razinaprivilegije', models.IntegerField(blank=True, db_column='RazinaPrivilegije', null=True)),
            ],
            options={
                'db_table': 'Korisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kuharica',
            fields=[
                ('idkuharica', models.IntegerField(db_column='IDKuharica', primary_key=True, serialize=False)),
                ('naslov', models.CharField(blank=True, db_column='Naslov', max_length=200, null=True)),
                ('datumizrade', models.DateField(blank=True, db_column='DatumIzrade', null=True)),
            ],
            options={
                'db_table': 'Kuharica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('idproizvod', models.IntegerField(db_column='IDproizvod', primary_key=True, serialize=False)),
                ('imeproizvod', models.CharField(blank=True, db_column='ImeProizvod', max_length=200, null=True)),
                ('energijapr', models.DecimalField(blank=True, db_column='EnergijaPr', decimal_places=5, max_digits=10, null=True)),
                ('masnocepr', models.DecimalField(blank=True, db_column='MasnocePr', decimal_places=5, max_digits=10, null=True)),
                ('bjelancevinepr', models.DecimalField(blank=True, db_column='BjelancevinePr', decimal_places=5, max_digits=10, null=True)),
                ('ugljikohidratipr', models.DecimalField(blank=True, db_column='UgljikohidratiPr', decimal_places=5, max_digits=10, null=True)),
                ('solpr', models.DecimalField(blank=True, db_column='SolPr', decimal_places=5, max_digits=10, null=True)),
                ('masapr', models.DecimalField(blank=True, db_column='MasaPr', decimal_places=5, max_digits=10, null=True)),
                ('zmkiselinepr', models.DecimalField(blank=True, db_column='ZMKiselinePr', decimal_places=5, max_digits=10, null=True)),
                ('seceripr', models.DecimalField(blank=True, db_column='SeceriPr', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Proizvod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('idrecept', models.IntegerField(db_column='IDrecept', primary_key=True, serialize=False)),
                ('velicinaporcija', models.IntegerField(blank=True, db_column='VelicinaPorcija', null=True)),
                ('vrijemepripreme', models.TimeField(blank=True, db_column='VrijemePripreme', null=True)),
                ('datumizrade', models.DateField(blank=True, db_column='DatumIzrade', null=True)),
            ],
            options={
                'db_table': 'Recept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slike',
            fields=[
                ('idslika', models.IntegerField(db_column='IDslika', primary_key=True, serialize=False)),
                ('slika', models.BinaryField(blank=True, db_column='Slika', null=True)),
            ],
            options={
                'db_table': 'Slike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komentarkuharica',
            fields=[
                ('korisnickoime', models.OneToOneField(db_column='KorisnickoIme', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.korisnik')),
                ('sadrzajkomentarar', models.CharField(blank=True, db_column='SadrzajKomentaraR', max_length=2048, null=True)),
                ('odgovornakomentarr', models.CharField(blank=True, db_column='OdgovorNaKomentarR', max_length=2048, null=True)),
                ('ocjenak', models.IntegerField(blank=True, db_column='OcjenaK', null=True)),
            ],
            options={
                'db_table': 'KomentarKuharica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Komentarrecept',
            fields=[
                ('korisnickoime', models.OneToOneField(db_column='KorisnickoIme', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.korisnik')),
                ('sadrzajkomentarar', models.CharField(blank=True, db_column='SadrzajKomentaraR', max_length=2048, null=True)),
                ('odgovornakomentarr', models.CharField(blank=True, db_column='OdgovorNaKomentarR', max_length=2048, null=True)),
                ('ocjenar', models.IntegerField(blank=True, db_column='OcjenaR', null=True)),
            ],
            options={
                'db_table': 'KomentarRecept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Konzumirao',
            fields=[
                ('korisnickoime', models.OneToOneField(db_column='KorisnickoIme', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.korisnik')),
                ('datum', models.DateField(blank=True, db_column='Datum', null=True)),
            ],
            options={
                'db_table': 'Konzumirao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Korak',
            fields=[
                ('idrecept', models.OneToOneField(db_column='IDrecept', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.recept')),
                ('opissl', models.CharField(blank=True, db_column='OpisSl', max_length=2048, null=True)),
                ('opiskorak', models.CharField(blank=True, db_column='OpisKorak', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'Korak',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oznakeproizvoda',
            fields=[
                ('idproizvod', models.OneToOneField(db_column='IDProizvod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.proizvod')),
            ],
            options={
                'db_table': 'OznakeProizvoda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Potrebnisastojci',
            fields=[
                ('idrecept', models.OneToOneField(db_column='IDrecept', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.recept')),
                ('kolicina', models.DecimalField(blank=True, db_column='Kolicina', decimal_places=5, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'PotrebniSastojci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pratikorisnika',
            fields=[
                ('korisnickoime_1', models.OneToOneField(db_column='KorisnickoIme_1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.korisnik')),
            ],
            options={
                'db_table': 'PratiKorisnika',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Privilegiranikorisnik',
            fields=[
                ('korisnickoime', models.OneToOneField(db_column='KorisnickoIme', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.korisnik')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=200, null=True)),
                ('biografija', models.CharField(blank=True, db_column='Biografija', max_length=2048, null=True)),
            ],
            options={
                'db_table': 'PrivilegiraniKorisnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restrikcija',
            fields=[
                ('imedijeta', models.OneToOneField(db_column='ImeDijeta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.dijeta')),
            ],
            options={
                'db_table': 'Restrikcija',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sadrzi',
            fields=[
                ('idrecept', models.OneToOneField(db_column='IDRecept', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.recept')),
            ],
            options={
                'db_table': 'Sadrzi',
                'managed': False,
            },
        ),
    ]
