# Generated by Django 4.2.7 on 2023-12-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dijeta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dodatneoznake',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='komentarkuharica',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='komentarrecept',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='konzumirao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='korak',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='korisnik',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='kuharica',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oznakeproizvoda',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='potrebnisastojci',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pratikorisnika',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='privilegiranikorisnik',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proizvod',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recept',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='restrikcija',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sadrzi',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='slike',
            options={'managed': True},
        ),
    ]
