# Generated by Django 4.2.7 on 2023-12-21 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dijeta_options_alter_dodatneoznake_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentarkuharica',
            name='idkuharica',
            field=models.ForeignKey(db_column='IDKuharica', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.kuharica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='komentarrecept',
            name='idrecept',
            field=models.ForeignKey(db_column='IDrecept', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.recept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='konzumirao',
            name='idrecept',
            field=models.ForeignKey(db_column='IDrecept', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.recept'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korak',
            name='idslika',
            field=models.ForeignKey(db_column='IDslika', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.slike'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='korisnik',
            name='imedijeta',
            field=models.ForeignKey(blank=True, db_column='ImeDijeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.dijeta'),
        ),
        migrations.AddField(
            model_name='kuharica',
            name='korisnickoime',
            field=models.ForeignKey(blank=True, db_column='KorisnickoIme', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.korisnik'),
        ),
        migrations.AddField(
            model_name='oznakeproizvoda',
            name='idozn',
            field=models.ForeignKey(db_column='IDOzn', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.dodatneoznake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='potrebnisastojci',
            name='idproizvod',
            field=models.ForeignKey(db_column='IDproizvod', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.proizvod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pratikorisnika',
            name='korisnickoime_2',
            field=models.ForeignKey(db_column='KorisnickoIme_2', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pratikorisnika_korisnickoime_2_set', to='api.korisnik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privilegiranikorisnik',
            name='idslika',
            field=models.ForeignKey(blank=True, db_column='IDslika', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.slike'),
        ),
        migrations.AddField(
            model_name='proizvod',
            name='idslika',
            field=models.ForeignKey(blank=True, db_column='IDslika', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.slike'),
        ),
        migrations.AddField(
            model_name='recept',
            name='korisnickoime',
            field=models.ForeignKey(blank=True, db_column='KorisnickoIme', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.korisnik'),
        ),
        migrations.AddField(
            model_name='restrikcija',
            name='idozn',
            field=models.ForeignKey(db_column='IDOzn', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.dodatneoznake'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sadrzi',
            name='idkuharica',
            field=models.ForeignKey(db_column='IDKuharica', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.kuharica'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='komentarkuharica',
            unique_together={('korisnickoime', 'idkuharica')},
        ),
        migrations.AlterUniqueTogether(
            name='komentarrecept',
            unique_together={('korisnickoime', 'idrecept')},
        ),
        migrations.AlterUniqueTogether(
            name='konzumirao',
            unique_together={('korisnickoime', 'idrecept')},
        ),
        migrations.AlterUniqueTogether(
            name='korak',
            unique_together={('idrecept', 'idslika')},
        ),
        migrations.AlterUniqueTogether(
            name='oznakeproizvoda',
            unique_together={('idproizvod', 'idozn')},
        ),
        migrations.AlterUniqueTogether(
            name='potrebnisastojci',
            unique_together={('idrecept', 'idproizvod')},
        ),
        migrations.AlterUniqueTogether(
            name='pratikorisnika',
            unique_together={('korisnickoime_1', 'korisnickoime_2')},
        ),
        migrations.AlterUniqueTogether(
            name='restrikcija',
            unique_together={('imedijeta', 'idozn')},
        ),
        migrations.AlterUniqueTogether(
            name='sadrzi',
            unique_together={('idrecept', 'idkuharica')},
        ),
    ]
